version: 2

jobs:
  build:
    working_directory: ~/warnings-to-errors-webpack-plugin
    docker:
      - image: circleci/node:12.19.0
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Seoul"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependency
          command: |
            yarn install
            cd ./test
            cd ./v2-3 && yarn install && cd ..
            cd ./v4 && yarn install && cd ..
            cd ./v5 && yarn install && cd ..
            cd ..
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./test/v2-3/node_modules
            - ./test/v4/node_modules
            - ./test/v5/node_modules
            - ~/.yarn-cache
      - run:
          name: Test
          command: yarn test:coverage --maxWorkers=2
      - store_artifacts:
          path: coverage
          destination: coverage
